repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: ''
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        exclude: \.spec\.(js|jsx|ts|tsx)$

    - repo: https://github.com/pre-commit/mirrors-prettier
    rev: ''
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: tsc
        name: TypeScript compiler
        entry: tsc
        language: system
        types: [typescript]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ''
    hooks:
      - id: check-yarn-lock

  - repo: https://github.com/Yelp/detect-secrets
    rev: ''
    hooks:
      - id: detect-secrets
        args: ['--all-files']
        exclude: .secrets.baseline
