repos:
  -   repo: https://github.com/biomejs/pre-commit
      rev: ""  
      hooks:
       -  id: biome-check
          additional_dependencies: ["@biomejs/biome@1.9.4"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        exclude: '\.handlebars$'

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
