### Sing Up ###
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "name": "",
    "username": "",
    "email": "",
    "password": "",
}

### Login ###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "",
    "password": ""
}

### Get User ###
GET http://localhost:3000/users/testuser
token : 


### Update User Profile Picture ###
POST http://localhost:3000/users/testuser/uploadProfilePicture
token : 


### Get User ###
GET http://localhost:3000/settings/profile
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImVtYWlsIjoidGVzdDFAdGVzdC5jb20iLCJpYXQiOjE3MTI0NTM4MTl9.ub7XUn7dMpwImNw6FOWi0b3oJCwJE02zfx8snh3E8Io

### Upload Profile Picture ###
POST http://localhost:3000/settings/profile/uploadProfilePicture
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImVtYWlsIjoidGVzdDFAdGVzdC5jb20iLCJpYXQiOjE3MTI0NTM4MTl9.ub7XUn7dMpwImNw6FOWi0b3oJCwJE02zfx8snh3E8Io
Content-Type: multipart/form-data; boundary=mi-boundary

--mi-boundary
Content-Disposition: form-data; name="profilePicture"; filename="testPic.jpg"
Content-Type: image/jpeg

< ./testPic.jpg
--mi-boundary--